// <auto-generated />
namespace WellsOperaticSociety.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201609120903365_LongServiceAwards : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201609120903365_LongServiceAwards));
        
        string IMigrationMetadata.Id
        {
            get { return "201609121700299_201609120903365_LongServiceAwards"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
