//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contact Email
		///</summary>
		[ImplementPropertyType("contactEmail")]
		public string ContactEmail
		{
			get { return this.GetPropertyValue<string>("contactEmail"); }
		}

		///<summary>
		/// Date Applied For Membership: The date the member applied for membership
		///</summary>
		[ImplementPropertyType("dateAppliedForMembership")]
		public DateTime DateAppliedForMembership
		{
			get { return this.GetPropertyValue<DateTime>("dateAppliedForMembership"); }
		}

		///<summary>
		/// Date Approved For Membership: The date the member was approved by the committee for membership
		///</summary>
		[ImplementPropertyType("dateApprovedForMembership")]
		public DateTime DateApprovedForMembership
		{
			get { return this.GetPropertyValue<DateTime>("dateApprovedForMembership"); }
		}

		///<summary>
		/// Date Declined For Membership: The date the committee declined the user for membership
		///</summary>
		[ImplementPropertyType("dateDeclinedForMembership")]
		public DateTime DateDeclinedForMembership
		{
			get { return this.GetPropertyValue<DateTime>("dateDeclinedForMembership"); }
		}

		///<summary>
		/// Date Life Membership Granted: The date the committee awarded this user with life membership
		///</summary>
		[ImplementPropertyType("dateLifeMembershipGranted")]
		public DateTime DateLifeMembershipGranted
		{
			get { return this.GetPropertyValue<DateTime>("dateLifeMembershipGranted"); }
		}

		///<summary>
		/// Date Of Birth: The date the user was member was born. Used for tracking possible subscriptions
		///</summary>
		[ImplementPropertyType("dateOfBirth")]
		public DateTime DateOfBirth
		{
			get { return this.GetPropertyValue<DateTime>("dateOfBirth"); }
		}

		///<summary>
		/// Deactivated: Will stop the account showing up in searches etc essentially a soft delete
		///</summary>
		[ImplementPropertyType("deactivated")]
		public bool Deactivated
		{
			get { return this.GetPropertyValue<bool>("deactivated"); }
		}

		///<summary>
		/// First Name
		///</summary>
		[ImplementPropertyType("firstName")]
		public string FirstName
		{
			get { return this.GetPropertyValue<string>("firstName"); }
		}

		///<summary>
		/// Last Name
		///</summary>
		[ImplementPropertyType("lastName")]
		public string LastName
		{
			get { return this.GetPropertyValue<string>("lastName"); }
		}

		///<summary>
		/// Mobile Number
		///</summary>
		[ImplementPropertyType("mobileNumber")]
		public string MobileNumber
		{
			get { return this.GetPropertyValue<string>("mobileNumber"); }
		}

		///<summary>
		/// Previous System Id: To be deleted
		///</summary>
		[ImplementPropertyType("previousSystemId")]
		public int PreviousSystemId
		{
			get { return this.GetPropertyValue<int>("previousSystemId"); }
		}

		///<summary>
		/// Previous Years: Any previous years with other societies. This will add to the overall count of their long service award
		///</summary>
		[ImplementPropertyType("previousYears")]
		public int PreviousYears
		{
			get { return this.GetPropertyValue<int>("previousYears"); }
		}

		///<summary>
		/// Stripe UserId: The user id that stripe supplies when a user sets up their subscription
		///</summary>
		[ImplementPropertyType("stripeUserId")]
		public string StripeUserId
		{
			get { return this.GetPropertyValue<string>("stripeUserId"); }
		}

		///<summary>
		/// Telephone Number
		///</summary>
		[ImplementPropertyType("telephoneNumber")]
		public string TelephoneNumber
		{
			get { return this.GetPropertyValue<string>("telephoneNumber"); }
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}

		///<summary>
		/// Vehicle Registration 1
		///</summary>
		[ImplementPropertyType("vehicleRegistration1")]
		public string VehicleRegistration1
		{
			get { return this.GetPropertyValue<string>("vehicleRegistration1"); }
		}

		///<summary>
		/// Vehicle Registration 2
		///</summary>
		[ImplementPropertyType("vehicleRegistration2")]
		public string VehicleRegistration2
		{
			get { return this.GetPropertyValue<string>("vehicleRegistration2"); }
		}
	}
}
