#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Reports\LongServiceReport.cshtml"
    using WellsOperaticSociety.Models.Enums;
    
    #line default
    #line hidden
    using WellsOperaticSociety.PreCompiledViews;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Reports/LongServiceReport.cshtml")]
    public partial class _Views_Reports_LongServiceReport_cshtml : System.Web.Mvc.WebViewPage<WellsOperaticSociety.Models.ReportModels.LongServiceModel>
    {
        public _Views_Reports_LongServiceReport_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Reports\LongServiceReport.cshtml"
  
    //TODO: ADD in page header for styling
    var subList = new List<List<WellsOperaticSociety.Models.MemberModels.LongServiceAward>>();
    var breakPoint = 40;
    if (Model != null && Model.DueAwards.Any())
    {
        var chunkCount = Model.DueAwards.Count() / breakPoint;

        if (Model.DueAwards.Count % breakPoint > 0)
        {
            chunkCount++;
        }

        for (var i = 0; i < chunkCount; i++)
        {
            subList.Add(Model.DueAwards.Skip(i * breakPoint).Take(breakPoint).ToList());
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<html>\r\n<head>\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
        table {
            border-collapse: collapse;
            display: inline-block;
            width: 33%;
        }

        table, th, td {
            border: 1px solid;
        }

        .title {
            text-align: center;
        }

            .title p {
                font-size: 0.8rem;
                color: #a9a9a9;
            }
    </style>
</head>
<body>
");

WriteLiteral("    ");

            
            #line 47 "..\..\Views\Reports\LongServiceReport.cshtml"
Write(Html.Partial("~/Views/Reports/ReportHeader.cshtml", new ViewDataDictionary { { "baseUri", Model.BaseUri} }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n        <h2>Due Long Service Awards</h2>\r\n        <p>As of ");

            
            #line 50 "..\..\Views\Reports\LongServiceReport.cshtml"
            Write(DateTime.Now.ToString("D"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n    </div>\r\n");

            
            #line 52 "..\..\Views\Reports\LongServiceReport.cshtml"
    
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Reports\LongServiceReport.cshtml"
     if (subList.Any())
    {
        foreach (var list in subList)
        {

            
            #line default
            #line hidden
WriteLiteral("            <table");

WriteLiteral(" id=\"upcomingAwards\"");

WriteLiteral(">\r\n                <thead>\r\n                    <tr>\r\n                        <th" +
">Award</th>\r\n                        <th>Member</th>\r\n                    </tr>\r" +
"\n                </thead>\r\n                <tbody>\r\n");

            
            #line 64 "..\..\Views\Reports\LongServiceReport.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Reports\LongServiceReport.cshtml"
                     foreach (var award in list)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>");

            
            #line 67 "..\..\Views\Reports\LongServiceReport.cshtml"
                            Write(WellsOperaticSociety.Utilities.EnumHelper<NodaLongServiceAward>.GetDisplayValue(award.Award));

            
            #line default
            #line hidden
WriteLiteral(" </td>\r\n                            <td>");

            
            #line 68 "..\..\Views\Reports\LongServiceReport.cshtml"
                            Write(award.MemberDetails != null ? award.MemberDetails.Name : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(" </td>\r\n                        </tr>\r\n");

            
            #line 70 "..\..\Views\Reports\LongServiceReport.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n");

            
            #line 73 "..\..\Views\Reports\LongServiceReport.cshtml"
        }

    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">No awards are due yet</div>\r\n");

            
            #line 79 "..\..\Views\Reports\LongServiceReport.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
