#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WellsOperaticSociety.PreCompiledViews;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Reports/ReportHeader.cshtml")]
    public partial class _Views_Reports_ReportHeader_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Reports_ReportHeader_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" style=\"width: 100%; text-align: right;\"");

WriteLiteral(">\r\n    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 55), Tuple.Create("\"", 106)
            
            #line 2 "..\..\Views\Reports\ReportHeader.cshtml"
, Tuple.Create(Tuple.Create("", 61), Tuple.Create<System.Object, System.Int32>(ViewBag.BaseUri
            
            #line default
            #line hidden
, 61), false)
, Tuple.Create(Tuple.Create("", 77), Tuple.Create("/Images/Logo-Black-250x42.png", 77), true)
);

WriteLiteral(" />\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
