#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
    using WellsOperaticSociety.Models.ReportModels;
    
    #line default
    #line hidden
    using WellsOperaticSociety.PreCompiledViews;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Reports/VehicleRegistrationReport.cshtml")]
    public partial class _Views_Reports_VehicleRegistrationReport_cshtml : System.Web.Mvc.WebViewPage<List<VehicleRegistrationModel>>
    {
        public _Views_Reports_VehicleRegistrationReport_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
  
    //TODO: ADD in page header for styling
    var subList = new List<List<VehicleRegistrationModel>>();
    var breakPoint = 40;
    if (Model != null && Model.Any())
    {
        var chunkCount = Model.Count() / breakPoint;

        if (Model.Count % breakPoint > 0)
        {
            chunkCount++;
        }

        for (var i = 0; i < chunkCount; i++)
        {
            subList.Add(Model.Skip(i * breakPoint).Take(breakPoint).ToList());
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<html>\r\n<head>\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n        table {\r\n            border-collapse: collapse;\r\n            display: " +
"inline-block;\r\n            width: 33%;\r\n        }\r\n        table, th, td {\r\n    " +
"        border: 1px solid;\r\n        }    \r\n</style>\r\n</head>\r\n<body>\r\n\r\n");

            
            #line 38 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
     if (subList.Any())
    {

        foreach (var list in subList)
        {

            
            #line default
            #line hidden
WriteLiteral("            <table>\r\n                <thead>\r\n                <tr>\r\n             " +
"       <th>Registration</th>\r\n                    <th>Owner</th>\r\n              " +
"  </tr>\r\n                </thead>\r\n                <tbody>\r\n");

            
            #line 51 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                     foreach (var record in list)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>");

            
            #line 54 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                           Write(record.Registration);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 55 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                           Write(record.Member.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        </tr>\r\n");

            
            #line 57 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n");

            
            #line 60 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
