#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WellsOperaticSociety.PreCompiledViews;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Reports/VehicleRegistrationReport.cshtml")]
    public partial class _Views_Reports_VehicleRegistrationReport_cshtml : System.Web.Mvc.WebViewPage<List<WellsOperaticSociety.Models.MemberModels.Member>>
    {
        public _Views_Reports_VehicleRegistrationReport_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<html>\r\n<head></head>\r\n<body>\r\n");

            
            #line 5 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
     if (Model != null && Model.Any())
    {

            
            #line default
            #line hidden
WriteLiteral("        <table>\r\n            <thead>\r\n            <tr>\r\n                <th>Regis" +
"tration</th>\r\n                <th>Owner</th>\r\n            </tr>\r\n            </t" +
"head>\r\n            <tbody>\r\n");

            
            #line 15 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                 foreach (var member in Model)
                {
                    if (member.VehicleRegistration1.IsNotNullOrEmpty())
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>");

            
            #line 20 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                           Write(member.VehicleRegistration1);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 21 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                           Write(member.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        </tr>\r\n");

            
            #line 23 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                    }
                    if (member.VehicleRegistration2.IsNotNullOrEmpty())
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>");

            
            #line 27 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                           Write(member.VehicleRegistration2);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 28 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                           Write(member.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        </tr>\r\n");

            
            #line 30 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n");

            
            #line 34 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
