#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
    using WellsOperaticSociety.Models.ReportModels;
    
    #line default
    #line hidden
    using WellsOperaticSociety.PreCompiledViews;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Reports/VehicleRegistrationReport.cshtml")]
    public partial class _Views_Reports_VehicleRegistrationReport_cshtml : System.Web.Mvc.WebViewPage<VehicleRgeistrationViewModel>
    {
        public _Views_Reports_VehicleRegistrationReport_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
  
    //TODO: ADD in page header for styling
    var subList = new List<List<VehicleRegistrationModel>>();
    var breakPoint = 40;
    if (Model.RegistrationList != null && Model.RegistrationList.Any())
    {
        var chunkCount = Model.RegistrationList.Count() / breakPoint;

        if (Model.RegistrationList.Count % breakPoint > 0)
        {
            chunkCount++;
        }

        for (var i = 0; i < chunkCount; i++)
        {
            subList.Add(Model.RegistrationList.Skip(i * breakPoint).Take(breakPoint).ToList());
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<html>\r\n<head>\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
        table {
            border-collapse: collapse;
            display: inline-block;
            width: 33%;
        }
        table, th, td {
            border: 1px solid;
        }    
        .title {
            text-align: center;
        }

        .title p {
            font-size: 0.8rem;
            color: #a9a9a9
        }
</style>
</head>
<body>
");

WriteLiteral("    ");

            
            #line 45 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
Write(Html.Partial("~/Views/Reports/ReportHeader.cshtml", new ViewDataDictionary { { "baseUri", Model.BaseUri } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h2>Vehicle Registrations</h2>\r\n    <p>As of ");

            
            #line 48 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
        Write(DateTime.Now.ToString("D"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n</div>\r\n");

            
            #line 50 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
    
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
     if (subList.Any())
    {

        foreach (var list in subList)
        {

            
            #line default
            #line hidden
WriteLiteral("            <table>\r\n                <thead>\r\n                <tr>\r\n             " +
"       <th>Registration</th>\r\n                    <th>Owner</th>\r\n              " +
"  </tr>\r\n                </thead>\r\n                <tbody>\r\n");

            
            #line 63 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                     foreach (var record in list)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n                            <td>");

            
            #line 66 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                           Write(record.Registration);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            <td>");

            
            #line 67 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                           Write(record.Member.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        </tr>\r\n");

            
            #line 69 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n");

            
            #line 72 "..\..\Views\Reports\VehicleRegistrationReport.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
