#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WellsOperaticSociety.PreCompiledViews;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Emails/MembershipRenewalCommingUp.cshtml")]
    public partial class _Views_Emails_MembershipRenewalCommingUp_cshtml : System.Web.Mvc.WebViewPage<WellsOperaticSociety.Models.EmailModels.MembershipRenewal>
    {
        public _Views_Emails_MembershipRenewalCommingUp_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<html>\r\n<head>\r\n");

WriteLiteral("    ");

            
            #line 5 "..\..\Views\Emails\MembershipRenewalCommingUp.cshtml"
Write(Html.Partial("~/Views/Emails/EmailStyling.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Emails\MembershipRenewalCommingUp.cshtml"
Write(Html.Partial("~/Views/Emails/EmailHeader.cshtml", new ViewDataDictionary { { "baseUri", Model.BaseUri } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <p>\r\n        It\'s that time of year again.\r\n        <br />\r\n        <br />\r" +
"\n        Your ");

            
            #line 13 "..\..\Views\Emails\MembershipRenewalCommingUp.cshtml"
        Write(Model.MembershipType);

            
            #line default
            #line hidden
WriteLiteral(" membership is running out and will be due for renewal on\r\n    </p>\r\n    <p>\r\n   " +
"     <b>");

            
            #line 16 "..\..\Views\Emails\MembershipRenewalCommingUp.cshtml"
      Write(Model.DateDue.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral(@"</b>
    </p>
<p>Don't worry this is just a reminder. You can either renew your membership by giving payment to our treasurer or, you can sign up to a subscription in the members area of the website and not have to worry about paying your subs ever again.</p>
<p>If you have already signed up to a subscription then please don't worry this is just a warning that the payment will come out shortly.</p>
<p>
    Wells Operatic Society
</p>
");

WriteLiteral("    ");

            
            #line 23 "..\..\Views\Emails\MembershipRenewalCommingUp.cshtml"
Write(Html.Partial("~/Views/Emails/EmailFooter.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
