#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WellsOperaticSociety.PreCompiledViews;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Emails/PaymentFailed.cshtml")]
    public partial class _Views_Emails_PaymentFailed_cshtml : System.Web.Mvc.WebViewPage<WellsOperaticSociety.Models.EmailModels.PaymentFailed>
    {
        public _Views_Emails_PaymentFailed_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<html>\r\n<head>\r\n");

WriteLiteral("    ");

            
            #line 5 "..\..\Views\Emails\PaymentFailed.cshtml"
Write(Html.Partial("~/Views/Emails/EmailStyling.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Emails\PaymentFailed.cshtml"
Write(Html.Partial("~/Views/Emails/EmailHeader.cshtml", new ViewDataDictionary { { "baseUri", Model.BaseUri } }));

            
            #line default
            #line hidden
WriteLiteral(@"
    <p>
        Oops! Your latest payment failed to go through. Please log on and update your credit card info to keep your subscription active. The details are included below.,
    </p>
    <p>
        ======================================<br/>
        RECEIPT #: ");

            
            #line 14 "..\..\Views\Emails\PaymentFailed.cshtml"
              Write(Model.ReceiptId);

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n        <br />\r\n        Bill to:<br />\r\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Views\Emails\PaymentFailed.cshtml"
   Write(Model.BillTo);

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n        <br />\r\n        Running from  ");

            
            #line 19 "..\..\Views\Emails\PaymentFailed.cshtml"
                 Write(Model.StartDate);

            
            #line default
            #line hidden
WriteLiteral(" to ");

            
            #line 19 "..\..\Views\Emails\PaymentFailed.cshtml"
                                     Write(Model.EndDate);

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n        <br />\r\n        Total: £");

            
            #line 21 "..\..\Views\Emails\PaymentFailed.cshtml"
           Write(Model.Amount);

            
            #line default
            #line hidden
WriteLiteral(@"<br />
        <br />
        ======================================<br />
        NEED TO CANCEL:<br />
        ======================================<br />
        <br />
        If you don’t need your subscription anymore,<br />
        go to your account and cancel at any time.<br />
        <br />
        If you have any questions, please contact us.
    </p>
    <p>
        Wells Operatic Society
    </p>
");

WriteLiteral("    ");

            
            #line 35 "..\..\Views\Emails\PaymentFailed.cshtml"
Write(Html.Partial("~/Views/Emails/EmailFooter.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
