#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WellsOperaticSociety.PreCompiledViews;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Emails/ShowVouchers.cshtml")]
    public partial class _Views_Emails_ShowVouchers_cshtml : System.Web.Mvc.WebViewPage<WellsOperaticSociety.Models.EmailModels.ShowVoucher>
    {
        public _Views_Emails_ShowVouchers_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<html>\r\n<head>\r\n");

WriteLiteral("    ");

            
            #line 5 "..\..\Views\Emails\ShowVouchers.cshtml"
Write(Html.Partial("~/Views/Emails/EmailStyling.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Emails\ShowVouchers.cshtml"
Write(Html.Partial("~/Views/Emails/EmailHeader.cshtml", new ViewDataDictionary { { "baseUri", Model.BaseUri } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <p>\r\n        Hi ");

            
            #line 10 "..\..\Views\Emails\ShowVouchers.cshtml"
      Write(Model.Member.Name);

            
            #line default
            #line hidden
WriteLiteral(",\r\n    </p>\r\n    <p>\r\n        Pre booking tickets for ");

            
            #line 13 "..\..\Views\Emails\ShowVouchers.cshtml"
                           Write(Model.Function.DisplayName);

            
            #line default
            #line hidden
WriteLiteral(" starts on ");

            
            #line 13 "..\..\Views\Emails\ShowVouchers.cshtml"
                                                                 Write(Model.DateActive);

            
            #line default
            #line hidden
WriteLiteral(". Follow the instructions below to get your tickets.\r\n    </p>\r\n<p>\r\n    You can " +
"either follow this link<br/>\r\n    <br/>\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 540), Tuple.Create("\"", 558)
            
            #line 18 "..\..\Views\Emails\ShowVouchers.cshtml"
, Tuple.Create(Tuple.Create("", 547), Tuple.Create<System.Object, System.Int32>(Model.Link
            
            #line default
            #line hidden
, 547), false)
);

WriteLiteral(">");

            
            #line 18 "..\..\Views\Emails\ShowVouchers.cshtml"
                     Write(Model.Link);

            
            #line default
            #line hidden
WriteLiteral(@"</a><br/>
    <br/>
    which will take you to the boxoffice and will apply your voucher automatically, or follow the steps below:
    <ol>
        <li>Go to the the show on the website and click on the book tickets link. This may not appear until the pre booking date has been reached</li>
        <li>Click on the ""Enter Voucher Code"" link at the top of the page</li>
        <li>Enter your voucher code<br/>
            <br/>
            <b>");

            
            #line 26 "..\..\Views\Emails\ShowVouchers.cshtml"
          Write(Model.Key);

            
            #line default
            #line hidden
WriteLiteral(@"</b><br/>
            <br/>
            and click apply
        </li>
        <li>You should now be able to book tickets</li>
    </ol>
    N.B If there are no tickets displayed when you select a show date then either you have not entered your voucher correctly, or it might have been invalidated for some reason. Please contact us to resolve this.
</p>
    <p>
        Wells Operatic Society
    </p>
");

WriteLiteral("    ");

            
            #line 37 "..\..\Views\Emails\ShowVouchers.cshtml"
Write(Html.Partial("~/Views/Emails/EmailFooter.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
