#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WellsOperaticSociety.PreCompiledViews;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Emails/SubscriptionCreated.cshtml")]
    public partial class _Views_Emails_SubscriptionCreated_cshtml : System.Web.Mvc.WebViewPage<WellsOperaticSociety.Models.EmailModels.SubscriptionCreated>
    {
        public _Views_Emails_SubscriptionCreated_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("    <html>\r\n    <head>\r\n");

WriteLiteral("        ");

            
            #line 4 "..\..\Views\Emails\SubscriptionCreated.cshtml"
   Write(Html.Partial("~/Views/Emails/EmailStyling.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </head>\r\n    <body>\r\n");

WriteLiteral("        ");

            
            #line 7 "..\..\Views\Emails\SubscriptionCreated.cshtml"
   Write(Html.Partial("~/Views/Emails/EmailHeader.cshtml", new ViewDataDictionary { { "baseUri", Model.BaseUri } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <p>\r\n            Thanks for setting up your subscription for membership" +
" at the level ");

            
            #line 9 "..\..\Views\Emails\SubscriptionCreated.cshtml"
                                                                           Write(Model.PlanName);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n        <p>\r\n            You will get a receipt shortly if your p" +
"ayment has been successful.\r\n        </p>\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Emails\SubscriptionCreated.cshtml"
   Write(Html.Partial("~/Views/Emails/EmailFooter.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
